apiVersion: v1
kind: Pod
metadata:
  name: authorization
  namespace: searchcombat
  labels:
    env: production
spec:
  containers:
  - name: authorization
    image: sumit0skribe/authorization:sha-8466a8a
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
    resources:
      requests:
        memory: "300Mi"
        cpu: "250m"
      limits:
        memory: "400Mi"
        cpu: "500m"